 #define	PORTA_CLK	SIM_SCGC5_PORTA_MASK
 #define	PORTB_CLK	SIM_SCGC5_PORTB_MASK
 #define	PORTC_CLK	SIM_SCGC5_PORTC_MASK
 #define	PORTD_CLK	SIM_SCGC5_PORTD_MASK
 #define	PORTE_CLK	SIM_SCGC5_PORTE_MASK
 #define PPP_CLK	PORTA_CLK | PORTD_CLK | PORTE_CLK | PORTB_CLK | PORTC_CLK
 
 
//    SIM_SCGC5 |= (SIM_SCGC5_PORTA_MASK
//                  | SIM_SCGC5_PORTB_MASK
//                  | SIM_SCGC5_PORTC_MASK
//                  | SIM_SCGC5_PORTD_MASK
//                  | SIM_SCGC5_PORTE_MASK );